_BASE_: "faster_rcnn_R_50_FPN_3x.yaml"
DATASETS:
  TRAIN: ("fracture_train",)
  TEST: ("fracture_val",)
MODEL:
  RPN:
    HEAD_NAME: "StandardRPNHead"
    BBOX_REG_WEIGHTS: (10,10,5,5,1)
  ANCHOR_GENERATOR:
    NAME: "RotatedAnchorGenerator"
    ANGLES: [[-45,-22.5,0,22.5,45,67.5]]
  ROI_HEADS:
    NAME: "RROIHeads"
    BATCH_SIZE_PER_IMAGE: 512
    NUM_CLASSES: 2
    SCORE_THRESH_TEST: 0.5
  PROPOSAL_GENERATOR:
    NAME: "RRPN"
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignRotated"
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 1.0)
    NUM_CONV: 4
  ROI_MASK_HEAD:
    NUM_CONV: 8
  MASK_ON: False
  BACKBONE:
    FREEZE_AT: 6
DATALOADER:
  NUM_WORKERS: 0
  FILTER_EMPTY_ANNOTATIONS: True 
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.01
SOLVER:
  BASE_LR: 0.0002
  GAMMA: 0.5
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 4
  MAX_ITER: 15000
  STEPS: [3000, 7000, 9000, 13000]